#pragma once
#include <UnknownIR/Context.h>
#include <UnknownIR/Type.h>
#include <UnknownIR/User.h>
#include <UnknownIR/Value.h>
#include <UnknownIR/Constant.h>
#include <UnknownIR/GlobalVariable.h>
#include <UnknownIR/LocalVariable.h>
#include <UnknownIR/FlagsVariable.h>
#include <UnknownIR/OpCode.h>
#include <UnknownIR/Instruction.h>
#include <UnknownIR/IRBuilder.h>
#include <UnknownIR/Module.h>
#include <UnknownIR/BasicBlock.h>
#include <UnknownIR/Function.h>
#include <UnknownIR/OverloadStream.h>
